sudo: false

language: go

go:
  - 1.6

addons:
  apt:
    packages:
    - python-virtualenv
    - graphviz

env:
  global:
    - secure: "YSwtFrMqh4oUvdSQTXBXMHHLWeQgyNEL23ChIZwU0nuDGIcQZ65kipu0PzefedtUbK4ieC065YCUi4UDDh6gPotB/Wu1pnYg3dyQ7rFvhaVYAAUEpajAdXZhlx+7+J8a4FZMeC/kqiahxoRgLbthF9019ouIqhGB9zHKI6/yZwc="
    - secure: "V7OjWrfQ8UbktgT036jYQPb/7GJT3Ol9LObDr8FYlzsQ+F1uj2wLac6ePuxcOS4FwWOJinWGM1h+JiFkbxbyFqfRNJ0jj0O2p93QyDojxFVOn1mXqqvV66KFqAWR2Vzkny/gDvj8LTvdB1cgAIm2FNOkQc6E1BFnyWS2sN9ea5E="
    - secure: "OxiVNmre2JzUszwPNNilKDgIqtfX2gnRSsVz6nuySB1uO2yQsOQmKWJ9cVYgH2IB5H8eWXKOhexcSE28kz6TPLRuEcU9fnqKY3uEkdwm7rJfz9lf+7C4bJEUdA1OIzJppjnWUiXxD7CEPL1DlnMZM24eDQYqa/4WKACAgkK53gE="
before_install:
  - git config user.email "sitter@kde.org"
  - git config user.name "Blue Systems Travis Builder"
  #- git fetch -v origin sftp:sftp
  #- git merge -v sftp -m 'automerge'
  - ln -s $GOPATH/src/github.com/apachelogger $GOPATH/src/github.com/smira
  - virtualenv env
  - . env/bin/activate
  - pip install --upgrade setuptools
  - pip install boto requests python-swiftclient sftpserver
install:
  - make prepare
  - ssh-keygen -t rsa -q -P "" -f /home/travis/.ssh/id_rsa


script: make travis

matrix:
    allow_failures:
        - go: tip

branches:
  only:
  - blue-systems


notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
